# Generated by Django 3.2.8 on 2021-12-23 11:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('phone', models.CharField(max_length=12)),
                ('option', models.TextField(verbose_name=(('Complaint', 'Complaint'), ('Business Enquiry', 'Business Enquiry')))),
                ('desc', models.TextField()),
                ('msg', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('phone', models.CharField(max_length=12)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('alias', models.CharField(max_length=100)),
                ('father', models.CharField(max_length=100)),
                ('placeofbirth', models.CharField(max_length=200)),
                ('dateofbirth', models.DateField()),
                ('gender', models.TextField(verbose_name=(('male', 'male'), ('female', 'female')))),
                ('martial', models.TextField(verbose_name=(('Married', 'Married'), ('Unmarried', 'Unmarried')))),
                ('nationality', models.CharField(max_length=12)),
                ('language', models.TextField(max_length=100)),
                ('contactnum', models.CharField(max_length=10)),
                ('contactnum2', models.CharField(max_length=10)),
                ('adhar', models.CharField(max_length=12)),
                ('Linkno', models.CharField(max_length=10)),
                ('Occupation', models.CharField(max_length=100)),
                ('nameofcompany', models.CharField(max_length=100)),
                ('ownername', models.CharField(max_length=100)),
                ('ownerno', models.CharField(max_length=10)),
                ('socityname', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('namestay', models.CharField(max_length=100)),
                ('relationship', models.CharField(max_length=100)),
                ('numb', models.CharField(max_length=10)),
                ('address2', models.CharField(max_length=100)),
                ('address3', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=14)),
                ('pincode', models.PositiveIntegerField()),
                ('police', models.CharField(max_length=100)),
                ('period', models.CharField(max_length=10)),
                ('presentsameperma', models.TextField(max_length=10)),
                ('peraddress', models.CharField(max_length=100)),
                ('pervillcity', models.CharField(max_length=100)),
                ('state2', models.CharField(max_length=12)),
                ('pincode2', models.PositiveIntegerField()),
                ('police2', models.CharField(max_length=100)),
                ('period2', models.CharField(max_length=10)),
                ('image1', models.ImageField(upload_to='formimage/')),
                ('image2', models.ImageField(upload_to='Aadhaarfront/')),
                ('image3', models.ImageField(upload_to='Aadhaarback/')),
                ('image4', models.ImageField(upload_to='Rental/')),
              
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('email_verified', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
